
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ravindra
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fleek
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    env_file: .env
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: dramatiq app.tasks.job_tasks
    env_file: .env
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
